eu-digital-identity-wallet/eudi-app-android-wallet-ui

proximity-feature/src/main/java/eu/europa/ec/proximityfeature/interactor/ProximityQRInteractor.kt, proximity-feature/src/test/java/eu/europa/ec/proximityfeature/interactor/TestProximityQRInteractor.kt, test-logic/src/main/java/eu/europa/ec/testlogic/base/ActivityHelper.kt
- Changed interactor's startQrEngagement() function to be (all of it) surrounded by a `flow{ }` builder block so that (all of) it is run on Dispatchers.IO + catching possible exceptions (safeAsync), and not just the walletCorePresentationController.events flow.
- Also removed its .cancellable() call since flows built with the `flow{ }` builder are cancellable by default.
- Added a helper function for Tests, that allows the creation of an Android Activity.
=> Adds unit tests for ProximityQRInteractor.

issuance-feature/src/main/java/eu/europa/ec/issuancefeature/ui/document/details/DocumentDetailsScreen.kt, presentation-feature/src/main/java/eu/europa/ec/presentationfeature/ui/loading/PresentationLoadingViewModel.kt, proximity-feature/src/main/java/eu/europa/ec/proximityfeature/ui/loading/ProximityLoadingViewModel.kt
1. Disable Icon for deletion of Document if state is loading, in Document Details.
2. If the User presses the hardware back button on the Success Screen, in the OID4VP-same device flow, the app should have the same behavior as if they pressed the "Continue" button.
=> Minor enhancements

common-feature/src/main/java/eu/europa/ec/commonfeature/ui/request/model/RequestDocumentItemUi.kt, common-feature/src/main/java/eu/europa/ec/commonfeature/ui/request/transformer/RequestTransformer.kt, common-feature/src/main/java/eu/europa/ec/commonfeature/util/TestsData.kt, dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/interactor/DashboardInteractor.kt, issuance-feature/src/main/java/eu/europa/ec/issuancefeature/interactor/document/AddDocumentInteractor.kt, issuance-feature/src/main/java/eu/europa/ec/issuancefeature/interactor/document/DocumentDetailsInteractor.kt, issuance-feature/src/test/java/eu/europa/ec/issuancefeature/interactor/document/TestAddDocumentInteractor.kt, issuance-feature/src/test/java/eu/europa/ec/issuancefeature/interactor/document/TestDocumentDetailsInteractor.kt, presentation-feature/src/test/java/eu/europa/ec/presentationfeature/interactor/TestPresentationLoadingInteractor.kt, proximity-feature/src/test/java/eu/europa/ec/proximityfeature/interactor/TestProximityRequestInteractor.kt, test-feature/src/main/java/eu/europa/ec/testfeature/Constants.kt
1 . Removed limitation issuing multiple PIDs and MDLs, Document Details document deletion will now clear the storage only for the first PID issued (based on issuing timestamp).
2. Retrieve the username and image from the main PID for dashboard.
3. Fix broken tests for AddDocument and ProximityRequest Interactors.
4. Add some new tests for DocumentDetails Interactor.
=> Unlocked multiple issued documents

resources-logic/src/main/res/values/strings.xml
- Add a space at the start of the "Why we need your data?" text.
=> Minor typo fix

ui-logic/src/main/java/eu/europa/ec/uilogic/component/ScalableText.kt
- The text style was not being recalculated when the textStyle changed, this commit fixes that by adding textStyle to the remember block.
=> Recalculate style of ScalableText when textStyle changes

dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/dashboard/DashboardViewModel.kt, ui-logic/src/main/java/eu/europa/ec/uilogic/component/wrap/WrapModalBottomSheet.kt
Replaced SIZE_SMALL and SIZE_MEDIUM with SPACING_SMALL and SPACING_MEDIUM for consistent spacing in the WrapModalBottomSheet component.
=> Refactor: Updated spacing in WrapModalBottomSheet

dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/dashboard/DashboardScreen.kt, dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/dashboard/DashboardViewModel.kt, ui-logic/src/main/java/eu/europa/ec/uilogic/component/wrap/WrapModalBottomSheet.kt
- Updated WrapModalBottomSheet to use ModalOptionUi instead of OptionListItemUi to make it more consistent with other components in the UI logic.
- Removed OptionListItemUi data class.
- Updated DashboardViewModel to use ModalOptionUi for bottom sheet options.
=> Refactor: Updated WrapModalBottomSheet to use ModalOptionUi.

presentation-feature/src/test/java/eu/europa/ec/presentationfeature/interactor/TestPresentationLoadingInteractor.kt, presentation-feature/src/test/java/eu/europa/ec/presentationfeature/interactor/TestPresentationRequestInteractor.kt, proximity-feature/src/test/java/eu/europa/ec/proximityfeature/interactor/TestProximityLoadingInteractor.kt, proximity-feature/src/test/java/eu/europa/ec/proximityfeature/interactor/TestProximityQRInteractor.kt, proximity-feature/src/test/java/eu/europa/ec/proximityfeature/interactor/TestProximityRequestInteractor.kt
Unit tests provided for proximity feature module interactors
Covering implementation of ProximityLoadingInteractor, modification for increased coverage in TestProximityQRInteractor and TestProximityRequestInteractor
Addresses: https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/issues/188
=> Test: Proximity feature interactors tests

common-feature/src/main/java/eu/europa/ec/commonfeature/ui/qr_scan/component/QrCodeAnalyzer.kt
Fix for https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/issues/207 
When creating PlanarYUVLuminanceSource change dataWidth parameter to plane.rowStride. YUV 420 images produced by the camera may have padding applied (rowStride is bigger than width).
The other change is to invoke QRCodeReader directly instead of MultiFormatReader. The setHints logic was not working correctly. MultiFormatReader was doing unnecessary work with scanning other code formats.
=> Fix QR code scanner

ui-logic/src/main/java/eu/europa/ec/uilogic/component/wrap/WrapButton.kt
- Removed `buttonColors` parameter from `WrapPrimaryButton` and `WrapSecondaryButton`.
- Updated `WrapPrimaryButton` and `WrapSecondaryButton` to use `buttonConfig.buttonColors` or default colors from `ButtonDefaults`.
=> Refactor: Update `WrapButton` component for improved color handling

ui-logic/src/main/java/eu/europa/ec/uilogic/component/wrap/WrapExpandableListItem.kt
- Updated `WrapExpandableListItem` to use `MaterialTheme.typography.bodyLarge` with bold font weight and `onSurface` color for the main content text.
- Removed the use of `LocalTextStyle` for styling the main content.
=> Refactor: Improve styling of WrapExpandableListItem

business-logic/src/main/java/eu/europa/ec/businesslogic/controller/storage/PrefsController.kt
Modified `getString` in `PrefsController` to return the `defaultValue` when the retrieved value is null, rather than only when the key-value pair is invalid. This is to correctly handle the case where a key is present but its associated value is null.
=> Refactor: Update string retrieval in PrefsController

assembly-logic/src/main/java/eu/europa/ec/assemblylogic/Application.kt, business-logic/src/main/java/eu/europa/ec/businesslogic/config/ConfigLogic.kt, core-logic/src/main/java/eu/europa/ec/corelogic/config/ConfigWalletCore.kt
- Moved the `revocationInterval` configuration from `ConfigLogic` to `WalletCoreConfig`.
- Updated `RevocationWorkManager` to use `walletCoreConfig.revocationInterval` instead of `configLogic.revocationInterval`.
- Added documentation for `revocationInterval`, `documentCategories` and `config` in `WalletCoreConfig`.
- Added a set of document categories and their associated identifiers to the `documentCategories` in `WalletCoreConfig`.
=> feat: Move Revocation Interval to Wallet Core Configuration

core-logic/src/main/java/eu/europa/ec/corelogic/worker/RevocationWorkManager.kt
-   Added a check in `RevocationWorkManager` to avoid adding a document to `revokedDocuments` multiple times if it's already stored as revoked.
-   Modified the logic to only add a document to `revokedDocuments` if it's not present in `storedRevokedDocuments` when its status is `Invalid` or `Suspended`.
=> feat: Enhance Revocation Handling in WorkManager

business-logic/src/main/java/eu/europa/ec/businesslogic/util/DateHelper.kt, dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/interactor/TransactionDetailsInteractor.kt, dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/interactor/TransactionsInteractor.kt, dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/transactions/detail/TransactionDetailsScreen.kt
- Updated `TransactionDetailsInteractor` and `TransactionsInteractor` to remove calls to `uppercaseAmPm`, directly formatting dates instead.
- Added a check to prevent rendering the "Data Shared" and "Data Signed" sections in `TransactionDetailsScreen` when there are no items to display.
- The section will now only be rendered if `dataItems` is not empty.
=> Dates localization

dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/documents/detail/DocumentDetailsScreen.kt
- Updated the revoked document message card to use `errorContainer` as the background color and `onErrorContainer` as the content color.
- Adjusted the revoked message text style to `bodyMedium`.
Add a description of the change here
=> Refactor: Update document details revoked message appearance

business-logic/src/demo/java/eu/europa/ec/businesslogic/config/RQESConfigImpl.kt, business-logic/src/dev/java/eu/europa/ec/businesslogic/config/RQESConfigImpl.kt, gradle/libs.versions.toml
This commit updates the RQES-UI SDK to version 0.2.1. 
The `RqesServiceConfig` has been removed and its properties are now part of `QtspData`.
=> Update RQES-UI SDK to version 0.2.1

authentication-logic/src/main/java/eu/europa/ec/authenticationlogic/controller/authentication/BiometricAuthenticationController.kt, authentication-logic/src/main/java/eu/europa/ec/authenticationlogic/di/LogicAuthenticationModule.kt, authentication-logic/src/main/java/eu/europa/ec/authenticationlogic/storage/PrefsBiometryStorageProvider.kt, authentication-logic/src/main/java/eu/europa/ec/authenticationlogic/storage/PrefsPinStorageProvider.kt, business-logic/src/main/java/eu/europa/ec/businesslogic/controller/crypto/CryptoController.kt, business-logic/src/main/java/eu/europa/ec/businesslogic/controller/crypto/KeystoreController.kt, business-logic/src/main/java/eu/europa/ec/businesslogic/controller/storage/PrefsController.kt, wiki/configuration.md
This commit introduces encryption for PIN storage within the `PrefsPinStorageProvider`.
Key changes:
- PINs are now encrypted using AES/GCM/NoPadding before being stored in SharedPreferences.
- The `CryptoController` is utilized for encryption and decryption operations.
- `KeystoreController` now manages a general-purpose secret key for cryptographic operations, replacing the biometric-specific key.
- Relevant methods in `CryptoController` and `KeystoreController` have been updated to reflect this change (e.g., `getBiometricCipher` to `getCipher`, `retrieveOrGenerateBiometricSecretKey` to `retrieveOrGenerateSecretKey`).
- The `PrefKeys` interface and its implementation have been updated to use `CryptoAlias` instead of `BiometricAlias`.
- Dependency injection for `PrefsPinStorageProvider` …
=> Refactor: Enhance PIN storage security with encryption

app/proguard-rules.pro
This commit adds `okhttp3.internal.Util` to the ProGuard rules to suppress warnings.
=> ProGuard: Ignore okhttp3.internal.Util warnings

dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/home/HomeScreen.kt
The `WrapModalBottomSheet` component was removed from `HomeScreenSheetContent` as it was redundant. The `ModalBottomSheetLayout` in the parent `HomeScreen` already handles the modal behavior.
This change simplifies the `HomeScreenSheetContent` by removing the unnecessary wrapper and passing the `SheetState` directly from the parent.
Add a description of the change here
=> Refactor: Remove WrapModalBottomSheet from HomeScreenSheetContent

dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/documents/detail/DocumentDetailsScreen.kt
The background color of the animated card in the `DocumentDetailsScreen` has been removed. The card now uses the default container color.
=> Remove background color for animated card in DocumentDetailsScreen

fastlane/Fastfile, gradle/libs.versions.toml
This commit updates the `rqesUiSDK` version to `0.3.1` in `gradle/libs.versions.toml`.
Additionally, it refactors the `prepare_binary` lane in `fastlane/Fastfile`:
- Uses `File.join` for constructing paths to improve cross-platform compatibility.
- Adds checks to ensure the original APK exists before attempting to rename.
- Implements error handling for the renaming process.
- Uses `FileUtils.mv` and `FileUtils.rm_f` for more robust file operations.
- Improves output messages for clarity.
=> Bump rqesUiSDK to 0.3.1 and improve APK renaming in Fastlane

dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/documents/detail/DocumentDetailsScreen.kt, dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/transactions/detail/TransactionDetailsScreen.kt, issuance-feature/src/main/java/eu/europa/ec/issuancefeature/ui/add/AddDocumentScreen.kt, issuance-feature/src/main/java/eu/europa/ec/issuancefeature/ui/offer/DocumentOfferScreen.kt
This commit refactors the navigation bar padding in several screens.
Key changes:
- In `AddDocumentScreen.kt`, the `navigationBarsPadding` modifier was removed from the main content `Column` and added to the `Spacer` within the `Options` composable, conditional on `footerIsShown`.
- In `DocumentDetailsScreen.kt`, `navigationBarsPadding` was removed from the main `Column` and added to the `WrapButton` within the `Column`.
- In `TransactionDetailsScreen.kt`, `navigationBarsPadding` was removed from the outer `Column` and added to the inner scrollable `Column`.
- In `DocumentOfferScreen.kt`, the bottom padding was removed from the `MainContent` modifier.
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
=> Refactor: Adjust navigation bar padding

common-feature/src/main/java/eu/europa/ec/commonfeature/ui/qr_scan/QrScanScreen.kt, dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/documents/detail/DocumentDetailsScreen.kt, dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/documents/list/DocumentsScreen.kt, dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/home/HomeScreen.kt, dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/transactions/detail/TransactionDetailsScreen.kt, dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/transactions/list/TransactionsScreen.kt, issuance-feature/src/main/java/eu/europa/ec/issuancefeature/ui/add/AddDocumentScreen.kt, proximity-feature/src/main/java/eu/europa/ec/proximityfeature/ui/qr/ProximityQRScreen.kt, ui-logic/src/main/java/eu/europa/ec/uilogic/extension/ModifierExtensions.kt
This commit introduces and utilizes a new `paddingFrom` Modifier extension function to simplify how padding is applied based on `PaddingValues` from Scaffold.
Key changes:
- Added `Modifier.paddingFrom()` extension function in `ModifierExtensions.kt`. This function allows selectively applying padding (top, start, end, bottom) from a given `PaddingValues` object.
- Replaced manual calculation and application of padding using `paddingValues.calculateTopPadding()`, `calculateStartPadding()`, `calculateEndPadding()`, and `LocalLayoutDirection.current` with the new `paddingFrom` extension in the following screens:
- `HomeScreen.kt`
- `TransactionsScreen.kt`
- `QrScanScreen.kt`
- `AddDocumentScreen.kt`
- `DocumentDetailsScreen.kt`
- `ProximityQRScreen.kt`
- `DocumentsScreen.kt`
- …
=> Refactor: Use `paddingFrom` extension for simplified padding logic

assembly-logic/src/main/AndroidManifest.xml
This commit changes the `android.hardware.nfc` feature from `required="true"` to `required="false"` in the `AndroidManifest.xml`. This allows the application to be installed on devices that do not have NFC capabilities.
=> Make NFC feature optional

resources-logic/src/main/java/eu/europa/ec/resourceslogic/theme/values/ThemeColors.kt
Removes the word "NEW" from a comment describing dark theme fixed accent roles in `ThemeColors.kt`.
=> Fix(theme): Remove "NEW" from comment
