common-feature/src/main/java/eu/europa/ec/commonfeature/ui/qr_scan/QrScanScreen.kt
common-feature/src/main/java/eu/europa/ec/commonfeature/util/DocumentHelper.kt
core-logic/src/main/java/eu/europa/ec/corelogic/model/DocumentType.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/dashboard/DashboardScreen.kt
issuance-feature/src/main/java/eu/europa/ec/issuancefeature/ui/document/add/AddDocumentViewModel.kt
issuance-feature/src/main/java/eu/europa/ec/issuancefeature/ui/success/SuccessViewModel.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/component/ErrorInfo.kt

- Rename DocumentType's property from codeName to nameSpace to better reflect its nature.
- Throttle clicks on ErrorInfo.
- Change AddDocumentViewModel's getOnBackAction() signature to not return null functions.
- Align the content of ErrorInfo to its Center.
(before)
(after)
(before)
(after)

Enhancement - minor changes

---

core-logic/src/demo/java/eu/europa/ec/corelogic/config/ConfigWalletCoreImpl.kt
core-logic/src/dev/java/eu/europa/ec/corelogic/config/ConfigWalletCoreImpl.kt
wiki/how_to_build.md

* Updates on how_to_build.md for when running everything locally.
* Fixes Verifier Client Id when running locally.

Readme updates + fixes client_id for when it's running locally.

---

README.md

Update readme file according to QA review

---

assembly-logic/src/main/AndroidManifest.xml
assembly-logic/src/main/java/eu/europa/ec/assemblylogic/Application.kt
business-logic/build.gradle.kts
business-logic/src/main/java/eu/europa/ec/businesslogic/controller/log/LogController.kt
business-logic/src/main/java/eu/europa/ec/businesslogic/di/LogicBusinessModule.kt
core-logic/src/demo/java/eu/europa/ec/corelogic/config/ConfigWalletCoreImpl.kt
core-logic/src/dev/java/eu/europa/ec/corelogic/config/ConfigWalletCoreImpl.kt
core-logic/src/main/java/eu/europa/ec/corelogic/controller/WalletCoreLogController.kt
core-logic/src/main/java/eu/europa/ec/corelogic/di/LogicCoreModule.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/di/FeatureDashboardModule.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/interactor/DashboardInteractor.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/dashboard/DashboardScreen.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/dashboard/DashboardViewModel.kt
dashboard-feature/src/test/java/eu/europa/ec/dashboardfeature/interactor/TestDashboardInteractor.kt
gradle/libs.versions.toml
resources-logic/src/main/res/drawable/ic_open_new.xml
resources-logic/src/main/res/values/strings.xml
resources-logic/src/main/res/xml/provider_paths.xml
settings.gradle.kts
ui-logic/src/main/java/eu/europa/ec/uilogic/component/AppIcons.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/component/ModalOptionUi.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/extension/ContextExtensions.kt

…ng, Implementation for logs retrieval throught the dashboard modal.

New Logs mechanism with persistence storage caching and runtime logging, Implementation for logs retrieval throught the dashboard modal.

---

business-logic/src/main/java/eu/europa/ec/businesslogic/validator/FormValidator.kt
business-logic/src/test/java/eu/europa/ec/businesslogic/validator/TestFormValidator.kt
common-feature/src/main/java/eu/europa/ec/commonfeature/ui/qr_scan/QrScanViewModel.kt

Renamed Rule ValidateProjectUrl to ValidateUrl

minor refactor for formValidator

---

common-feature/src/main/java/eu/europa/ec/commonfeature/ui/biometric/BiometricViewModel.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/component/wrap/WrapExpandableCard.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/component/wrap/WrapModalBottomSheet.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/component/wrap/WrapPinTextField.kt

- WrapPinTextField corrections
- Ui bug fixes for new Compose update

Fixed Pin Input duplicate results, fixed various ui issues after compose update

---

ui-logic/src/main/java/eu/europa/ec/uilogic/component/ClickableText.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/component/content/ContentTitle.kt

- Brought Compose's ClickableText Composable inside the project.

Refactor: Replace deprecated ClickableText.

---

common-feature/src/main/java/eu/europa/ec/commonfeature/util/TestsData.kt
dashboard-feature/src/test/java/eu/europa/ec/dashboardfeature/interactor/TestDashboardInteractor.kt
test-feature/src/main/java/eu/europa/ec/testfeature/Constants.kt

- Unit tests added for DashboardInteractor, ensuring high coverage of cases in interactor's implementation, added a mock unsigned document and data to use in test
- Applied changes after reviewing for code conformity

Test: Dashboard interactor unit tests

---

authentication-logic/src/main/java/eu/europa/ec/authenticationlogic/controller/authentication/DeviceAuthenticationController.kt
common-feature/src/main/java/eu/europa/ec/commonfeature/interactor/DeviceAuthenticationInteractor.kt
common-feature/src/test/java/eu/europa/ec/commonfeature/interactor/TestBiometricInteractor.kt
common-feature/src/test/java/eu/europa/ec/commonfeature/interactor/TestDeviceAuthenticationInteractor.kt
common-feature/src/test/java/eu/europa/ec/commonfeature/interactor/TestQrScanInteractor.kt

- Unit tests created for common-feature module interactors, covering implementation of BiometricInteractor, DeviceAuthenticationInteractor and QrScanInteractor
- Applied changes suggested after reviewing
Addresses: https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/issues/188

Test: Common Feature interactors unit tests

---

common-feature/src/main/java/eu/europa/ec/commonfeature/ui/request/RequestViewModel.kt

This commit updates the logic for enabling the share button in the Request Screen (for both Presentation and Proximity flows).
The share button will now only be enabled if either of the following cases is true:
- At least one verification(required) item is selected.
- At least one optional field is selected.
This ensures the share button is correctly enabled based on user selections.

Fix: Enable share button if at least one verification item or optional field is selected

---

presentation-feature/src/test/java/eu/europa/ec/presentationfeature/interactor/TestPresentationLoadingInteractor.kt
presentation-feature/src/test/java/eu/europa/ec/presentationfeature/interactor/TestPresentationRequestInteractor.kt

Unit tests provided for presentation feature module interactors
Covering implementation of PresentationRequestInteractor, added a test case PresentationLoadingInteractor, corrections applied 
Addresses: https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/issues/188

Test: Presentation Feature interactors unit tests

---

common-feature/src/main/java/eu/europa/ec/commonfeature/ui/loading/LoadingScreen.kt
common-feature/src/main/java/eu/europa/ec/commonfeature/ui/loading/LoadingViewModel.kt
presentation-feature/src/main/java/eu/europa/ec/presentationfeature/ui/loading/PresentationLoadingViewModel.kt
proximity-feature/src/main/java/eu/europa/ec/proximityfeature/ui/loading/ProximityLoadingViewModel.kt

Presentation Loading Screen should start not cancellable to avoid service interruptions

---

.github/PULL_REQUEST_TEMPLATE.md

improved pull request template

---

assembly-logic/build.gradle.kts
assembly-logic/src/main/AndroidManifest.xml
assembly-logic/src/main/java/eu/europa/ec/assemblylogic/Application.kt
assembly-logic/src/main/java/eu/europa/ec/assemblylogic/di/AssemblyModule.kt
build-logic/convention/build.gradle.kts
build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt
build-logic/convention/src/main/kotlin/EudiRqesPlugin.kt
build-logic/convention/src/main/kotlin/project/convention/logic/KotlinAndroid.kt
business-logic/build.gradle.kts
business-logic/src/demo/java/eu/europa/ec/businesslogic/config/ConfigLogicImpl.kt
business-logic/src/dev/java/eu/europa/ec/businesslogic/config/ConfigLogicImpl.kt
business-logic/src/main/java/eu/europa/ec/businesslogic/config/ConfigLogic.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/di/FeatureDashboardModule.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/interactor/DocumentSignInteractor.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/router/Graph.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/dashboard/DashboardViewModel.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/sign/DocumentSignScreen.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/sign/DocumentSignViewModel.kt
gradle/libs.versions.toml
resources-logic/src/main/res/drawable/ic_sign_document.xml
resources-logic/src/main/res/values/strings.xml
ui-logic/build.gradle.kts
ui-logic/src/main/java/eu/europa/ec/uilogic/component/AppIcons.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/container/EudiComponentActivity.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/navigation/RouterContract.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/navigation/helper/DeepLinkHelper.kt

RQES Implementation & Integration with the RQES UI SDK

RQES Implementation & Integration with the RQES UI SDK

---

business-logic/src/demo/java/eu/europa/ec/businesslogic/config/ConfigLogicImpl.kt
business-logic/src/demo/java/eu/europa/ec/businesslogic/config/RQESConfigImpl.kt
business-logic/src/dev/java/eu/europa/ec/businesslogic/config/ConfigLogicImpl.kt
business-logic/src/dev/java/eu/europa/ec/businesslogic/config/RQESConfigImpl.kt
wiki/configuration.md

RQES Config refactored

---

gradle/libs.versions.toml

Updated RQES SDK

---

business-logic/src/demo/java/eu/europa/ec/businesslogic/config/RQESConfigImpl.kt
business-logic/src/dev/java/eu/europa/ec/businesslogic/config/RQESConfigImpl.kt
gradle/libs.versions.toml
wiki/configuration.md

Updated to latest RQES SDK

---

wiki/configuration.md
wiki/how_to_build.md

Add a description of the change here

Readme files improvements

---

fastlane/Fastfile
fastlane/README.md

Added support to upload tags to EU repo as well on demo release

Added support to upload tags to EU repo as well on demo release

---

fastlane/Fastfile
fastlane/README.md

Fastlane changes for tagging

---

fastlane/Fastfile

Correction for tag pushing fastlane

Correction for tag pushing fastlane

---

gradle/libs.versions.toml

New RQES Sdk

---

app/build.gradle.kts
app/proguard-rules.pro

Activated minification for release builds

Activated minification for release builds

---

common-feature/src/main/java/eu/europa/ec/commonfeature/model/DocumentTypeUi.kt
common-feature/src/main/java/eu/europa/ec/commonfeature/ui/request/transformer/RequestTransformer.kt
core-logic/src/main/java/eu/europa/ec/corelogic/model/DocumentIdentifier.kt

Fixed Presentation mandatory fields section

Fixed Presentation mandatory fields section

---

authentication-logic/src/main/java/eu/europa/ec/authenticationlogic/controller/authentication/BiometricAuthenticationController.kt
authentication-logic/src/main/java/eu/europa/ec/authenticationlogic/controller/authentication/DeviceAuthenticationController.kt
common-feature/src/main/java/eu/europa/ec/commonfeature/interactor/BiometricInteractor.kt
common-feature/src/main/java/eu/europa/ec/commonfeature/interactor/DeviceAuthenticationInteractor.kt
common-feature/src/main/java/eu/europa/ec/commonfeature/ui/biometric/BiometricViewModel.kt
common-feature/src/main/java/eu/europa/ec/commonfeature/ui/loading/LoadingViewModel.kt
common-feature/src/test/java/eu/europa/ec/commonfeature/interactor/TestBiometricInteractor.kt
common-feature/src/test/java/eu/europa/ec/commonfeature/interactor/TestDeviceAuthenticationInteractor.kt
core-logic/src/main/java/eu/europa/ec/corelogic/controller/WalletCoreDocumentsController.kt
core-logic/src/main/java/eu/europa/ec/corelogic/controller/WalletCorePresentationController.kt
issuance-feature/src/main/java/eu/europa/ec/issuancefeature/interactor/document/AddDocumentInteractor.kt
issuance-feature/src/main/java/eu/europa/ec/issuancefeature/interactor/document/DocumentOfferInteractor.kt
issuance-feature/src/main/java/eu/europa/ec/issuancefeature/ui/document/add/AddDocumentViewModel.kt
issuance-feature/src/main/java/eu/europa/ec/issuancefeature/ui/document/code/DocumentOfferCodeViewModel.kt
issuance-feature/src/main/java/eu/europa/ec/issuancefeature/ui/document/offer/DocumentOfferViewModel.kt
issuance-feature/src/test/java/eu/europa/ec/issuancefeature/interactor/document/TestAddDocumentInteractor.kt
issuance-feature/src/test/java/eu/europa/ec/issuancefeature/interactor/document/TestDocumentOfferInteractor.kt
presentation-feature/src/main/java/eu/europa/ec/presentationfeature/interactor/PresentationLoadingInteractor.kt
presentation-feature/src/main/java/eu/europa/ec/presentationfeature/ui/loading/PresentationLoadingViewModel.kt
presentation-feature/src/test/java/eu/europa/ec/presentationfeature/interactor/TestPresentationLoadingInteractor.kt
proximity-feature/src/main/java/eu/europa/ec/proximityfeature/interactor/ProximityLoadingInteractor.kt
proximity-feature/src/main/java/eu/europa/ec/proximityfeature/ui/loading/ProximityLoadingViewModel.kt
proximity-feature/src/test/java/eu/europa/ec/proximityfeature/interactor/TestProximityLoadingInteractor.kt
test-feature/src/main/java/eu/europa/ec/testfeature/Constants.kt

User experience Improvements and Critical corrections for Device Authentication mechanism, Presentation logic improvements

User experience Improvements and Critical corrections for Device Authentication mechanism, Presentation logic improvements

---

common-feature/src/main/java/eu/europa/ec/commonfeature/ui/request/RequestViewModel.kt

Fix for Multiple presentation requests for same device scenario

Fix for Multiple presentation requests for same device scenario

---

wiki/configuration.md
wiki/how_to_build.md

Updated How to build and configuration readme files.

Updated How to build and configuration readme files.

---

common-feature/src/main/java/eu/europa/ec/commonfeature/ui/document_details/transformer/DocumentDetailsTransformer.kt
common-feature/src/main/java/eu/europa/ec/commonfeature/ui/request/transformer/RequestTransformer.kt
common-feature/src/main/java/eu/europa/ec/commonfeature/util/DocumentHelper.kt

Correction for claims calculation

Correction for claims calculation

---

README.md
wiki/configuration.md

Updated Readme to reflect the latest UI changes.

Refactor: Updates Readme.

---

resources-logic/src/main/res/values/strings.xml

- Updated "Search documents" to "Search Documents".
- Updated "Filter by issuer" to "Filter by Issuer".
- Updated "Filter by category" to "Filter by Category".
- Updated "Filter by state" to "Filter by State".
- Updated "Filter by expiry period" to "Filter by Expiry Period".

Refactor: Update Documents screen string resources

---

gradle/libs.versions.toml

RQES SDK Update

---

gradle/libs.versions.toml

Bump rqesUiSDK version to 0.1.4

Bump rqesUiSDK version to 0.1.4

---

dashboard-feature/src/test/java/eu/europa/ec/dashboardfeature/interactor/TestDocumentsInteractor.kt
issuance-feature/src/main/java/eu/europa/ec/issuancefeature/ui/document/add/AddDocumentViewModel.kt

- Enhanced deep link handling in `AddDocumentViewModel` by adding a new function `getDeepLinkAction` that returns a Pair of `Uri` and `DeepLinkAction`.
- Updated error handling to conditionally display errors based on the presence of a deep link action.
- Added a separate `handleDeepLink` function that accepts a `Uri` and `DeepLinkAction` to manage navigation logic.
- Improved code clarity by separating the retrieval of deep link actions from the handling of deep link navigation.
- Replaced direct `handleDeepLink` calls with `getDeepLinkAction` to allow for conditional error display and navigation based on the type of deep link.
- Improved `mockFilterableItem` to make the code more readable.
Please describe the tests that you ran to verify your …

feat: Deep link handling improvements in AddDocumentViewModel

---

core-logic/src/main/java/eu/europa/ec/corelogic/controller/WalletCoreDocumentsController.kt

- Updated `getTransactionLogs` to process and parse each retrieved transaction log using `toCoreTransactionLog`, `parseTransactionLog`, and `toTransactionLogData`.
- Added logic to handle and convert stored transaction logs into a structured `TransactionLogData` format.

feat: Retrieve transaction logs with parsing

---

dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/interactor/DocumentsInteractor.kt

- Updated document filtering logic in `DocumentsInteractor`.
- Modified `FILTER_BY_STATE_EXPIRED` to also check if the document is not revoked.
- Removed unnecessary checks from `FILTER_BY_STATE_VALID`.

Refactor: Improve document filtering by state

---

core-logic/src/main/java/eu/europa/ec/corelogic/worker/RevocationWorkManager.kt

-   **RevocationWorkManager**:
- Modified `doWork` to get the revoked documents and also the documents that were revoked before and now are valid.
- Added `removeRevokedDocumentsFromStorage` function to delete the revoked documents from storage.
- Added logic to remove revoked documents from storage if their status is changed from `Invalid/Suspended` to `Valid`.
- Changed `sendRevocationBroadcasts` to only send the broadcasts for the documents that are `Invalid/Suspended`.
- Added `notifyDocumentsList` function to send the broadcast to refresh the documents list when there is a change.
- Changed `doWork` to call `notifyDocumentsList` if there are revoked documents or documents that were revoked and now are valid.
Please describe the tests that …

feat: Enhance revocation handling in RevocationWorkManager

---

Gemfile.lock

fastlane plugins update

---

business-logic/src/main/java/eu/europa/ec/businesslogic/util/DateHelper.kt
common-feature/src/main/java/eu/europa/ec/commonfeature/ui/request/RequestScreen.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/interactor/TransactionsInteractor.kt
issuance-feature/src/main/java/eu/europa/ec/issuancefeature/interactor/transaction/TransactionDetailsInteractor.kt
issuance-feature/src/main/java/eu/europa/ec/issuancefeature/model/transaction/details/TransactionDetailsUi.kt
issuance-feature/src/main/java/eu/europa/ec/issuancefeature/ui/transaction/details/TransactionDetailsScreen.kt
issuance-feature/src/main/java/eu/europa/ec/issuancefeature/ui/transaction/details/TransactionDetailsViewModel.kt
resources-logic/src/main/res/values/strings.xml

Refactored Transaction Details:
- It now show the complete date time stamp of its creation date.
- In case it is 'Failed' then it appears in an Error Chip (instead of Success).
- Re-added (mocked) functionality for data deletion request and suspicious transaction reporting.

Transaction Details fixes and enhancements

---

dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/documents/detail/DocumentDetailsViewModel.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/navigation/RouterContract.kt

- Renamed `ISSUANCE_DOCUMENT_DETAILS` route to `DOCUMENT_DETAILS`.
- Renamed `ISSUANCE_TRANSACTION_DETAILS` route to `TRANSACTION_DETAILS`.
- Removed unused `PrimaryButtonPressed` event from `DocumentDetailsViewModel`.

Refactor: Update navigation routes for Document Details and Transaction Details Screens.

---

dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/interactor/DocumentDetailsInteractor.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/interactor/DocumentsInteractor.kt
dashboard-feature/src/test/java/eu/europa/ec/dashboardfeature/interactor/TestDocumentDetailsInteractor.kt

- Fixed Documents filtering for Revoked Documents
- Update DocumentDetailsInteractor bookmark parameters

Revocation filter fix

---

dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/transactions/detail/TransactionDetailsScreen.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/component/wrap/WrapButton.kt

- Disabled the "Request data deletion" button in `TransactionDetailsScreen`.
- Disabled the "Report suspicious transaction" button in `TransactionDetailsScreen`.
- Improve button disabled state colors

Disable Data Deletion and Report Suspicious Transaction buttons

---

business-logic/src/main/java/eu/europa/ec/businesslogic/util/DateHelper.kt
business-logic/src/main/java/eu/europa/ec/businesslogic/validator/FilterValidator.kt
business-logic/src/main/java/eu/europa/ec/businesslogic/validator/model/Filters.kt
core-logic/src/main/java/eu/europa/ec/corelogic/extension/TransactionLogDataExtensions.kt
core-logic/src/main/java/eu/europa/ec/corelogic/model/TransactionLogData.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/interactor/TransactionDetailsInteractor.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/interactor/TransactionsInteractor.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/model/FilterDateRangeSelectionData.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/model/FilterableTransactionItem.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/transactions/list/TransactionsScreen.kt
dashboard-feature/src/main/java/eu/europa/ec/dashboardfeature/ui/transactions/list/TransactionsViewModel.kt
ui-logic/src/main/java/eu/europa/ec/uilogic/component/FiltersDatePickerDialog.kt

Add a description of the change here

Restrict available dates in filter calendar

---

.gitignore
fastlane/Fastfile
wiki/verifier_proximity.md

Fastlane support to upload extra attachments to Github Releases

Fastlane support to upload extra attachments to Github Releases

---

common-feature/src/main/java/eu/europa/ec/commonfeature/util/TestsData.kt
test-feature/src/main/java/eu/europa/ec/testfeature/Constants.kt

Fixed some broken unit tests in TestDocumentDetailsInteractor.

Refactor:  Fixed broken unit tests

---

README.md

Added "This project is tested with BrowserStack." message for BrowserStack
Added browserstack message in the Readme file.

Added BrowserStack message
